Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2018-07, with the labels that each got.

#837 Test potential solution for generic-netf being 'special'
  .travis.yml
  ArchiSteamFarm.Tests/ArchiSteamFarm.Tests.csproj
  ArchiSteamFarm/ArchiSteamFarm.csproj
  appveyor.yml
Labels: Enhancement

#839 Try to limit number of parallel restores
  .travis.yml
  appveyor.yml
Labels: Enhancement

#843 Implement #841
  ArchiSteamFarm/Bot.cs
Labels: Done, Enhancement

#847 CI fixes
  ArchiSteamFarm.Tests/ArchiSteamFarm.Tests.csproj
  ArchiSteamFarm/ArchiSteamFarm.csproj
Labels: Bug, Enhancement

#844 Feature editorconfig
  .editorconfig
Labels: Enhancement

#820 Fix for #803
  ArchiSteamFarm/www/js/app.js
Labels: Enhancement, Evaluation

#856 Feature GET, DELETE /Api/GamesToRedeemInBackground/{Bot}
  ArchiSteamFarm/Bot.cs
  ArchiSteamFarm/IPC.cs
Labels: Enhancement

#863 Travis: Misc improvements
  .travis.yml
Labels: Enhancement

#858 IPC GUI Update Nr.10
  ArchiSteamFarm/www/css/_nightmode.min.css
  ArchiSteamFarm/www/css/app.css
  ArchiSteamFarm/www/index.html
  ArchiSteamFarm/www/js/adminlte.min.js
  ArchiSteamFarm/www/js/app.js
  ArchiSteamFarm/www/locale/strings.json
  ArchiSteamFarm/www/pages/bots.html
  ArchiSteamFarm/www/pages/commands.html
  ArchiSteamFarm/www/pages/editor.html
  ArchiSteamFarm/www/pages/generator.html
  ArchiSteamFarm/www/pages/log.html
Labels: Enhancement
