Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2019-08, with the labels that each got.

#1349 Feature handle ipc config changes
  ArchiSteamFarm/ASF.cs
  ArchiSteamFarm/IPC/ArchiKestrel.cs
  ArchiSteamFarm/Localization/Strings.Designer.cs
  ArchiSteamFarm/Localization/Strings.resx
  ArchiSteamFarm/SharedInfo.cs
Labels: Enhancement

#1210 Bump to .NET Framework 4.8
  ArchiSteamFarm.CustomPlugins.ExamplePlugin/ArchiSteamFarm.CustomPlugins.ExamplePlugin.csproj
  ArchiSteamFarm.Tests/ArchiSteamFarm.Tests.csproj
  ArchiSteamFarm/ArchiSteamFarm.csproj
  appveyor.yml
Labels: Enhancement, External

#1358 Fix wallet code redeeming due to Steam changes
  ArchiSteamFarm/Bot.cs
  ArchiSteamFarm/BotConfig.cs
  ArchiSteamFarm/Commands.cs
Labels: Enhancement

#1375 Add Fair trades to MatchActively
  ArchiSteamFarm/Json/Steam.cs
  ArchiSteamFarm/Statistics.cs
  ArchiSteamFarm/Trading.cs
Labels: Enhancement, Feedback welcome, Finished

#1260 AppVeyor: Bump VS2017 to VS2019
  appveyor.yml
Labels: Enhancement
