Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2020-09, with the labels that each got.

#1957 Fix permission check in !level
  ArchiSteamFarm/Commands.cs
Labels: Bug, Confirmed, Low priority

#1967 Fix empty string staying in dictionary
  ArchiSteamFarm/Bot.cs
Labels: Bug, Fixes required, Low priority

#1993 Fix wallet code redeeming
  ArchiSteamFarm/ArchiWebHandler.cs
  ArchiSteamFarm/Json/Steam.cs
Labels: Bug, Enhancement
