Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2020-04, with the labels that each got.

#1703 Use streams for http responses instead of strings where possible, replace HtmlAgilityPack with AngleSharp
  ArchiSteamFarm/ArchiSteamFarm.csproj
  ArchiSteamFarm/ArchiWebHandler.cs
  ArchiSteamFarm/CardsFarmer.cs
  ArchiSteamFarm/Json/Steam.cs
  ArchiSteamFarm/MobileAuthenticator.cs
  ArchiSteamFarm/SteamSaleEvent.cs
  ArchiSteamFarm/Utilities.cs
  ArchiSteamFarm/WebBrowser.cs
Labels: Breaking changes, Enhancement, Finished

#1725 Catch exceptions when creating HtmlDocument from stream
  ArchiSteamFarm/WebBrowser.cs
Labels: Enhancement, Fixes required

#1743 Make HasMobileAuthenticator part of API
  ArchiSteamFarm/Bot.cs
Labels: Enhancement
