Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2020-05, with the labels that each got.

#1789 CI enhancements
  .github/workflows/ci.yml
  .travis.yml
Labels: Enhancement

#1803 Fix Docker Images
  Dockerfile.Service.arm
  Dockerfile.Service.arm64
  Dockerfile.Service.x64
  Dockerfile.arm
  Dockerfile.arm64
  Dockerfile.x64
Labels: Bug

#1809 Fixed NullPropagation
  ArchiSteamFarm/WebBrowser.cs
Labels: Bug, Enhancement
