Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2020-02, with the labels that each got.

#1622 Match assets with descriptions by instance IDs as well
  ArchiSteamFarm/ArchiWebHandler.cs
  ArchiSteamFarm/Json/Steam.cs
Labels: Enhancement, Low priority

#1624 Add item_type_13 (MiniProfileBackground)
  ArchiSteamFarm/Json/Steam.cs
Labels: Enhancement, Low priority

#1634 Dockerfile: Use more common npm run alias
  Dockerfile.Service.arm
  Dockerfile.Service.x64
  Dockerfile.arm
  Dockerfile.x64
Labels: Enhancement

#1650 Use HttpVersion.Version20 instead of creating Version instance
  ArchiSteamFarm/WebBrowser.cs
Labels: Enhancement

#1652 Use IAsyncEnumerable for getting inventory
  ArchiSteamFarm/Actions.cs
  ArchiSteamFarm/ArchiSteamFarm.csproj
  ArchiSteamFarm/ArchiWebHandler.cs
  ArchiSteamFarm/Bot.cs
  ArchiSteamFarm/CardsFarmer.cs
  ArchiSteamFarm/Commands.cs
  ArchiSteamFarm/Statistics.cs
  ArchiSteamFarm/Trading.cs
Labels: Enhancement, Feedback welcome, Finished
