Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2021-05, with the labels that each got.

#2317 Manage package versions centrally
  ArchiSteamFarm.CustomPlugins.ExamplePlugin/ArchiSteamFarm.CustomPlugins.ExamplePlugin.csproj
  ArchiSteamFarm.CustomPlugins.PeriodicGC/ArchiSteamFarm.CustomPlugins.PeriodicGC.csproj
  ArchiSteamFarm.OfficialPlugins.SteamTokenDumper/ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.csproj
  ArchiSteamFarm.Tests/ArchiSteamFarm.Tests.csproj
  ArchiSteamFarm/ArchiSteamFarm.csproj
  Directory.Build.props
  Directory.Packages.props
Labels: Bug, Enhancement

#2326 Workflow enhancements
  .github/workflows/ci.yml
  .github/workflows/docker-ci.yml
  .github/workflows/publish.yml
Labels: Enhancement

#2330 Commands added:
  ArchiSteamFarm/Localization/Strings.Designer.cs
  ArchiSteamFarm/Localization/Strings.resx
  ArchiSteamFarm/Steam/Data/AccessTokenResponse.cs
  ArchiSteamFarm/Steam/Integration/ArchiWebHandler.cs
  ArchiSteamFarm/Steam/Interaction/Commands.cs
Labels: ✨ Enhancement, 🏁 Finished, 📢 Feedback welcome
