Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2021-06, with the labels that each got.

#2335 Rewrite SendMessage() functions to account for new rate-limits
  ArchiSteamFarm.Tests/SteamChatMessage.cs
  ArchiSteamFarm/Steam/Bot.cs
  ArchiSteamFarm/Steam/Integration/SteamChatMessage.cs
  ArchiSteamFarm/Storage/GlobalConfig.cs
Labels: ✨ Enhancement, 🏁 Finished, 🐛 Bug, 💥 Regression, 📢 Feedback welcome

#2343 Add controllers as services
  ArchiSteamFarm/IPC/Startup.cs
Labels: ✨ Enhancement

#2348 Implement splitting of steam messages on newlines
  ArchiSteamFarm.Tests/SteamChatMessage.cs
  ArchiSteamFarm/Steam/Integration/SteamChatMessage.cs
Labels: ✨ Enhancement, 📢 Feedback welcome
