Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2021-07, with the labels that each got.

#2370 Use ArchiHandler to fetch owned games
  ArchiSteamFarm/Steam/Integration/ArchiHandler.cs
  ArchiSteamFarm/Steam/Integration/ArchiWebHandler.cs
  ArchiSteamFarm/Steam/Interaction/Commands.cs
  Directory.Packages.props
Labels: ✨ Enhancement

#2372 Closes #2371
  ArchiSteamFarm/IPC/Integration/ApiAuthenticationMiddleware.cs
  ArchiSteamFarm/IPC/Startup.cs
Labels: ✨ Enhancement, 🏁 Finished, 📢 Feedback welcome

#2379 Fix GlobalConfig update via IPC removing IPCPassword
  ArchiSteamFarm/IPC/Controllers/Api/ASFController.cs
  ArchiSteamFarm/Storage/GlobalConfig.cs
Labels: 🐛 Bug

#2380 Set end year of assembly copyright during build process
  Directory.Build.props
Labels: ✨ Enhancement

#2390 Fix command mabadd working incorrectly
  ArchiSteamFarm/Steam/Interaction/Commands.cs
Labels: 🐛 Bug
