Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2022-02, with the labels that each got.

#2505 Split global statistics into per-bot RemoteConnection
  ArchiSteamFarm/Core/RemoteCommunication.cs
  ArchiSteamFarm/Steam/Bot.cs
  ArchiSteamFarm/Steam/Storage/BotConfig.cs
  ArchiSteamFarm/Storage/GlobalConfig.cs
Labels: ✨ Enhancement, 📢 Feedback welcome, 🏁 Finished

#2509 Fix permissions when proxifying commands
  ArchiSteamFarm/Steam/Interaction/Commands.cs
  Directory.Build.props
Labels: 🐛 Bug, 🔴 High priority

#2511 Add VR to UserInterfaceMode
  ArchiSteamFarm/Steam/Bot.cs
  ArchiSteamFarm/Steam/Integration/ArchiHandler.cs
  ArchiSteamFarm/Steam/Storage/BotConfig.cs
Labels: ✨ Enhancement, 📢 Feedback welcome
