Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2022-03, with the labels that each got.

#2533 Closes #2532
  .github/workflows/publish.yml
Labels: 🐛 Bug, 💥 Regression, ☝️ External

#2535 Correctly detect steam deck keyboard skins
  ArchiSteamFarm/Steam/Data/Asset.cs
  ArchiSteamFarm/Steam/Data/InventoryResponse.cs
Labels: ✨ Enhancement

#2539 Make license detectable by more automated systems (Rename LICENSE)
  .github/CONTRIBUTING.md
  ArchiSteamFarm/ArchiSteamFarm.csproj
  Dockerfile
  Dockerfile.Service
  LICENSE.txt
  README.md
Labels: ✨ Enhancement

#2545 Closes #2544
  ArchiSteamFarm/ArchiSteamFarm.csproj
  ArchiSteamFarm/IPC/Integration/LocalizationMiddleware.cs
  ArchiSteamFarm/IPC/Startup.cs
  ArchiSteamFarm/IPC/WebUtilities.cs
  Directory.Packages.props
Labels: 🐛 Bug
