Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2023-04, with the labels that each got.

#2878 Periodically check for outstanding trades. Closes #2871
  ArchiSteamFarm/Steam/Bot.cs
  ArchiSteamFarm/Steam/Storage/BotConfig.cs
Labels: ✨ Enhancement, 🏁 Finished

#2877 Implemented native web GUI support for plugins inside the ASF IPC. Closes #2876
  ArchiSteamFarm/IPC/Startup.cs
  ArchiSteamFarm/Plugins/Interfaces/IWebInterface.cs
  Directory.Build.props
Labels: ✨ Enhancement, 📢 Feedback welcome, 🏁 Finished

#2887 Check if bot online before checking for outstanding trades. Bugfix for #2871
  ArchiSteamFarm/Steam/Bot.cs
Labels: 🐛 Bug, ✨ Enhancement
