Repository JustArchiNET/ArchiSteamFarm, pull requests merged in 2024-03, with the labels that each got.

#3158 Flash console window on input request on Windows
  ArchiSteamFarm/Core/NativeMethods.cs
  ArchiSteamFarm/Core/OS.cs
  ArchiSteamFarm/NLog/Logging.cs
Labels: ✨ Enhancement, 📢 Feedback welcome, 🏁 Finished

#3164 Fix GetTradeOffer exception
  ArchiSteamFarm/Steam/Integration/ArchiWebHandler.cs
Labels: 🐛 Bug, ✨ Enhancement, ✔️ Confirmed

#3173 Add POST /Api/Plugins/Update
  ArchiSteamFarm/IPC/Controllers/Api/PluginsController.cs
  ArchiSteamFarm/IPC/Requests/PluginUpdateRequest.cs
Labels: ✨ Enhancement
